import { AnimatePresence,motion } from 'framer-motion'
import { BarChart3,Check,ChevronLeft,Clock3,Download,Flower2,Gift,History,ImageOff,LockKeyhole,LogOut,Plus,RefreshCw,Settings,ShieldCheck,Sparkles,Sprout,Star,Trash2,Volume2,type LucideIcon } from 'lucide-react'
import { useEffect,useRef,useState,type ReactNode } from 'react'
import { Link,Navigate,Outlet,Route,Routes,useNavigate } from 'react-router-dom'
import { plantWords } from './data'
import { categoryAccuracy,dayKey,getNextReviewQuestions } from './logic'
import { useGardenStore } from './store'
import type { AnswerRecord,Question,ReviewPlan,Reward,SessionMode,SessionSummary,WordItem } from './types'

const title=(s:string)=>s.replace(/\b\w/g,c=>c.toUpperCase())
const weekCutoff=Date.now()-7*86400000
const speak=(word:string)=>{if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.75;speechSynthesis.speak(u)}}
const makePlantQuestions=():Question[]=>[...plantWords].sort(()=>Math.random()-.5).map(item=>({item,type:'plant-category',options:[]}))

function PureImage({item,large=false}:{item:WordItem;large?:boolean}){const[failed,setFailed]=useState(false);return <div className={`word-art pure-image ${large?'word-art-large':''}`}>{failed?<ImageOff aria-label="圖片稍後可替換"/>:<img src={item.image} alt="" onError={()=>setFailed(true)}/>}</div>}
function StarJar(){const stars=useGardenStore(s=>s.wallet.currentStars);return <div className="star-jar" aria-label={`${stars} 分`}><Star fill="currentColor"/><strong>{stars}</strong></div>}
function Bunny({mood='wave'}:{mood?:'wave'|'jump'|'gentle'|'gift'}){return <motion.div className={`bunny bunny-${mood}`} animate={mood==='jump'?{y:[0,-18,0],rotate:[0,-8,8,0]}:{y:[0,-3,0]}} transition={{duration:mood==='jump'?.65:3,repeat:mood==='jump'?2:Infinity}} aria-label="Hattie's bunny friend"><div className="ear-row"><i/><i/></div><div className="bunny-face"><b>•</b><em>ᴗ</em><b>•</b></div><div className="bunny-body"><span>♡</span></div></motion.div>}
function ChildShell({children,back=true}:{children:ReactNode;back?:boolean}){return <main className="child-shell paper-scene"><header className="child-top">{back?<Link className="round-link" to="/" aria-label="Home"><ChevronLeft/></Link>:<span/>}<StarJar/></header>{children}</main>}

function HomePage(){return <main className="home-page paper-scene"><Link className="parent-link" to="/parent-login"><ShieldCheck/> Parent</Link><StarJar/><section className="home-hero"><Bunny/><div><h1><span>Hi</span> Hattie!</h1><p>Ready to review?</p></div></section><nav className="big-actions"><Link className="big-action green" to="/review"><Sprout/><span>Start Review</span></Link><Link className="big-action yellow" to="/plants"><Flower2/><span>Plant Game</span></Link><Link className="big-action blue" to="/garden"><Sparkles/><span>My Garden</span></Link></nav></main>}

function ReviewPage(){const mastery=useGardenStore(s=>s.mastery),records=useGardenStore(s=>s.records),plan=useGardenStore(s=>s.reviewPlan),startNew=useGardenStore(s=>s.startNewReviewCycle);if(plan.completedAt)return <CycleComplete plan={plan} startNew={startNew}/>;return <PracticeRunner key={plan.cycleId} initialQuestions={getNextReviewQuestions(plan,mastery,records)} initialMode="review" showPlanProgress/>}
function PlantsPage(){const[seed]=useState(makePlantQuestions);return <PracticeRunner initialQuestions={seed} initialMode="plants"/>}

function PracticeRunner({initialQuestions,initialMode,showPlanProgress=false}:{initialQuestions:Question[];initialMode:SessionMode;showPlanProgress?:boolean}){
  const answer=useGardenStore(s=>s.answer),complete=useGardenStore(s=>s.completeSession)
  const plan=useGardenStore(s=>s.reviewPlan)
  const[questions,setQuestions]=useState(initialQuestions),[mode,setMode]=useState(initialMode),[index,setIndex]=useState(0),[result,setResult]=useState<AnswerRecord|null>(null)
  const[sessionId,setSessionId]=useState(()=>crypto.randomUUID()),[started,setStarted]=useState(()=>Date.now()),[roundRecords,setRoundRecords]=useState<AnswerRecord[]>([]),[summary,setSummary]=useState<SessionSummary|null>(null)
  const advanceTimer=useRef<number|undefined>(undefined)
  const q=questions[index]
  const next=(records=roundRecords)=>{if(advanceTimer.current)window.clearTimeout(advanceTimer.current);if(index===questions.length-1){setSummary(complete(sessionId,mode,records))}else{setIndex(v=>v+1);setResult(null);setStarted(Date.now())}}
  const choose=(selected:string)=>{if(result)return;const r=answer(q.item,q.type,selected,(Date.now()-started)/1000,sessionId,mode),nextRecords=[...roundRecords,r];setResult(r);setRoundRecords(nextRecords);speak(q.item.word);advanceTimer.current=window.setTimeout(()=>next(nextRecords),r.isCorrect?1200:2000)}
  const begin=(nextQuestions:Question[],nextMode:SessionMode)=>{setQuestions(nextQuestions);setMode(nextMode);setIndex(0);setResult(null);setRoundRecords([]);setSummary(null);setSessionId(crypto.randomUUID());setStarted(Date.now())}
  if(summary)return <RoundComplete summary={summary} wrongQuestions={questions.filter(x=>summary.wrongWords.includes(x.item.word))} allQuestions={questions} onRedoWrong={qs=>begin(qs,'wrong-redo')} onRestart={()=>begin(questions,mode==='wrong-redo'?'wrong-redo':initialMode)}/>
  return <ChildShell><section className={`task-card ${q.type==='plant-category'?'plant-task':''}`}>{showPlanProgress&&<div className="plan-progress-child"><span>You are helping the garden grow!</span><strong>{plan.reviewedWords} / {plan.totalWords} words</strong><i><b style={{width:`${plan.reviewedWords/plan.totalWords*100}%`}}/></i></div>}<div className="progress"><span style={{width:`${(index+1)/questions.length*100}%`}}/></div><p className="eyebrow">{index+1} / {questions.length}</p><QuestionView question={q} choose={choose} result={result}/><AnimatePresence>{result&&<Feedback record={result} item={q.item} next={()=>next()}/>}</AnimatePresence></section></ChildShell>
}
function CycleComplete({plan,startNew}:{plan:ReviewPlan;startNew:()=>void}){return <ChildShell><section className="complete-card perfect-round"><div className="star-fireworks">✦ ★ ✦</div><Bunny mood="jump"/><h1>太棒了！Hattie 已完成全部單詞複習！</h1><p>{plan.reviewedWords} / {plan.totalWords} words reviewed</p><div className="finish-actions"><button onClick={startNew}>開始新一輪複習計劃</button><Link to="/parent/weak-words">查看錯題</Link><Link to="/">返回首頁</Link></div></section></ChildShell>}

function QuestionView({question,choose,result}:{question:Question;choose:(v:string)=>void;result:AnswerRecord|null}){
  const stateFor=(value:string)=>!result?'':value===result.correctAnswer?'option-correct':value===result.selectedAnswer?'option-wrong':'option-muted'
  if(question.type==='plant-category')return <div className="plant-question"><PureImage item={question.item} large/><div className="plant-info"><div className="plant-word-row"><h2>{title(question.item.word)}</h2><button className="speak-btn plant-speak" onClick={()=>speak(question.item.word)} aria-label={`Listen to ${question.item.word}`}><Volume2/> Listen</button></div><div className="plant-choices"><button className={stateFor('root')} disabled={!!result} onClick={()=>choose('root')}><strong>Root</strong><span>地下</span></button><button className={stateFor('above-ground')} disabled={!!result} onClick={()=>choose('above-ground')}><strong>Above Ground</strong><span>地上</span></button></div></div></div>
  const pictureToWord=question.type==='picture-to-word',listen=question.type==='listen-to-picture'
  return <><div className="question-prompt"><h2>{pictureToWord?'What is this?':listen?'Listen and choose!':title(question.item.word)}</h2><button className={`speak-btn ${listen?'listen-main':''}`} onClick={()=>speak(question.item.word)}><Volume2/>{listen?'Listen':'Hear it'}</button></div>{pictureToWord&&<PureImage item={question.item} large/>}<div className="answer-grid">{question.options.map((o,i)=><button key={o.word} className={`answer-option ${stateFor(o.word)}`} disabled={!!result} aria-label={pictureToWord?o.word:`picture option ${i+1}`} onClick={()=>choose(o.word)}>{pictureToWord?<strong>{title(o.word)}</strong>:<><PureImage item={o}/>{result&&o.word===result.correctAnswer&&<span className="revealed-answer">{title(o.word)}</span>}</>}</button>)}</div></>
}
function Feedback({record,item,next}:{record:AnswerRecord;item:WordItem;next:()=>void}){const plant=record.questionType==='plant-category';return <motion.div className={`feedback ${record.isCorrect?'correct':'wrong'}`} initial={{opacity:0,y:20,scale:.94}} animate={{opacity:1,y:0,scale:1}}><div className="feedback-symbol">{record.isCorrect?'✓':'×'}</div><Bunny mood={record.isCorrect?'jump':'gentle'}/><div><h3>{record.isCorrect?'Correct! Great job!':'Almost, Hattie!'}</h3><p>{plant?`${title(item.word)} grows ${item.category==='root'?'under the ground.':'above the ground.'}`:record.isCorrect?title(item.word):`The answer is ${item.word}.`}</p></div><button onClick={next}>Next <Check/></button>{record.isCorrect&&<motion.div className="flying-star" animate={{x:220,y:-350,scale:[1,1.5,.3]}}>★</motion.div>}</motion.div>}
function RoundComplete({summary,wrongQuestions,allQuestions,onRedoWrong,onRestart}:{summary:SessionSummary;wrongQuestions:Question[];allQuestions:Question[];onRedoWrong:(q:Question[])=>void;onRestart:()=>void}){
  return <ChildShell><section className={`complete-card ${summary.perfect?'perfect-round':''}`}>{summary.perfect&&<div className="star-fireworks">✦ ★ ✦</div>}<Bunny mood={summary.perfect?'jump':'gift'}/><div className="score-badge"><Star fill="currentColor"/><strong>{summary.score}</strong><span>分</span></div><h1>{summary.perfect?'太棒了！這一輪全對！':'做得很好，Hattie！'}</h1><p>{summary.perfect?'你獲得了 12 分！':`你獲得了 ${summary.score} 分，再試一次，看看能不能全對拿 12 分！`}</p><div className="round-stats"><span>第一次做對 <b>{summary.firstTryCorrectCount}/{summary.totalQuestions}</b></span><span>錯題 <b>{summary.wrongCount}</b></span></div><div className="finish-actions"><Link to="/">退出</Link><button className="wrong-redo" disabled={!wrongQuestions.length} onClick={()=>onRedoWrong(wrongQuestions)}>錯題再做</button><button onClick={()=>{void allQuestions;onRestart()}}><RefreshCw/> 重做</button></div>{!wrongQuestions.length&&<small>本輪沒有錯題！</small>}</section></ChildShell>
}

function GardenPage(){const w=useGardenStore(s=>s.wallet),sessions=useGardenStore(s=>s.sessions);return <ChildShell><section className="garden-page"><div className="garden-visual"><Bunny/><div className="garden-flower f1">✿</div><div className="garden-flower f2">✿</div></div><div className="garden-copy"><p className="eyebrow">My Garden</p><h1>{w.totalEarned>=50?'Butterfly garden':w.totalEarned>=25?'First flowers':w.totalEarned>=10?'Green sprout':'A tiny seed'}</h1><div className="garden-stats"><div><Star/><strong>{w.currentStars}</strong><span>My Points</span></div><div><Sprout/><strong>{sessions.length}</strong><span>Rounds</span></div><div><Check/><strong>{sessions.some(s=>s.date.startsWith(dayKey()))?'Yes!':'Not yet'}</strong><span>Played today</span></div></div><p>Ask Mommy or Daddy to open the Reward Shop.</p></div></section></ChildShell>}
function ParentLogin(){const login=useGardenStore(s=>s.login),nav=useNavigate();const[p,setP]=useState(''),[error,setError]=useState(false);return <main className="login-page paper-scene"><Link className="round-link" to="/"><ChevronLeft/></Link><section><LockKeyhole/><h1>家長入口</h1><p>請輸入家長密碼</p><input inputMode="numeric" value={p} onChange={e=>setP(e.target.value)} placeholder="密碼" aria-label="家長密碼"/>{error&&<p className="error-text">密碼不正確</p>}<button className="primary-button" onClick={()=>login(p)?nav('/parent'):setError(true)}>進入家長後台</button></section></main>}

const parentLinks=[['/parent',BarChart3,'總覽'],['/parent/history',History,'歷史記錄'],['/parent/weak-words',Sprout,'錯題分析'],['/parent/rewards',Gift,'獎勵商店'],['/parent/settings',Settings,'設定']]as const
function ParentLayout(){const ok=useGardenStore(s=>s.parentAuthed),logout=useGardenStore(s=>s.logout),nav=useNavigate();if(!ok)return <Navigate to="/parent-login" replace/>;return <div className="parent-shell"><aside><Link className="parent-brand" to="/"><Flower2/><span>Hattie 單詞花園</span></Link><nav>{parentLinks.map(([to,I,l])=><Link key={to} to={to}><I/>{l}</Link>)}</nav><button onClick={()=>{logout();nav('/')}}><LogOut/>退出家長模式</button></aside><main><Outlet/></main></div>}
function ParentHeader({titleText,subtitle}:{titleText:string;subtitle:string}){return <header className="parent-header"><div><p className="eyebrow">家長後台</p><h1>{titleText}</h1><p>{subtitle}</p></div><StarJar/></header>}
const accuracy=(rs:AnswerRecord[])=>rs.length?Math.round(rs.filter(r=>r.firstTryCorrect).length/rs.length*100):0
function Dashboard(){const records=useGardenStore(s=>s.records),sessions=useGardenStore(s=>s.sessions),w=useGardenStore(s=>s.wallet),plan=useGardenStore(s=>s.reviewPlan),startNew=useGardenStore(s=>s.startNewReviewCycle);const today=records.filter(r=>r.date.startsWith(dayKey())),week=records.filter(r=>new Date(r.date).getTime()>=weekCutoff),days=new Set(records.map(r=>r.date.slice(0,10))),reviewed=plan.items.filter(i=>i.reviewedInCurrentCycle),pending=plan.items.filter(i=>!i.reviewedInCurrentCycle);const metrics:Array<[string,string|number,LucideIcon]>=[['當前分數',w.currentStars,Star],['今日獲得',w.todayEarned,Sparkles],['今日正確率',`${accuracy(today)}%`,Check],['本週正確率',`${accuracy(week)}%`,BarChart3],['累計題數',records.length,History],['練習天數',days.size,Clock3],['完成輪次',sessions.length,Flower2]];return <><ParentHeader titleText="學習總覽" subtitle="查看 Hattie 的練習與得分情況"/><section className="panel review-plan-panel"><div><h2>本輪複習進度：{plan.reviewedWords} / {plan.totalWords}</h2><p>已複習 {reviewed.length} 個 · 未複習 {pending.length} 個 · 本輪錯題 {reviewed.filter(i=>i.wrongCountInCycle>0).length} 個 · 本輪全對單詞 {reviewed.filter(i=>i.firstTryCorrect).length} 個</p><i><b style={{width:`${plan.reviewedWords/plan.totalWords*100}%`}}/></i></div><button onClick={()=>confirm('確定開始新的完整複習週期嗎？')&&startNew()}>開始新一輪</button></section><div className="metric-grid">{metrics.map(([l,v,I])=><article key={l}><I/><span>{l}</span><strong>{v}</strong></article>)}</div><section className="panel plan-lists"><div><h2>已複習單詞</h2><table><thead><tr><th>單詞</th><th>第一次做對</th><th>最近複習</th><th>題型</th></tr></thead><tbody>{reviewed.map(i=><tr key={i.word}><td>{i.word}</td><td>{i.firstTryCorrect?'是':'否'}</td><td>{i.reviewedAt?.slice(0,10)}</td><td>{i.questionType}</td></tr>)}</tbody></table></div><div><h2>未複習單詞</h2><table><thead><tr><th>單詞</th><th>分類</th><th>安排</th></tr></thead><tbody>{pending.map(i=>{const word=plantWords.find(w=>w.word===i.word);return <tr key={i.word}><td>{i.word}</td><td>{word?.category??'alphabet'}</td><td>之後輪次</td></tr>})}</tbody></table></div></section><section className="panel"><h2>分類正確率</h2><div className="bars">{[['root','根莖類'],['above-ground','地上植物'],['alphabet','字母單詞'],['listen-to-picture','聽音選圖'],['picture-to-word','看圖選字'],['word-to-picture','看字選圖'],['plant-category','植物分類']].map(([c,l])=><div key={c}><span>{l}</span><i><b style={{width:`${categoryAccuracy(records,c)}%`}}/></i><strong>{categoryAccuracy(records,c)}%</strong></div>)}</div></section></>}
function HistoryPage(){const sessions=useGardenStore(s=>s.sessions);return <><ParentHeader titleText="歷史記錄" subtitle="每輪練習都會保存在此 iPad"/><section className="panel table-panel"><table><thead><tr><th>日期</th><th>模式</th><th>完成題數</th><th>第一次做對</th><th>錯題數</th><th>得分</th><th>全對</th><th>平均時間</th></tr></thead><tbody>{[...sessions].reverse().map(s=><tr key={s.sessionId}><td>{s.date.slice(0,10)}</td><td>{s.mode==='review'?'複習':s.mode==='plants'?'植物分類':'錯題再做'}</td><td>{s.totalQuestions}</td><td>{s.firstTryCorrectCount}</td><td>{s.wrongCount}</td><td>{s.score}</td><td>{s.perfect?'是':'否'}</td><td>{s.averageTimeSpent.toFixed(1)} 秒</td></tr>)}</tbody></table>{!sessions.length&&<Empty/>}</section></>}
function WeakWordsPage(){const records=useGardenStore(s=>s.records);const wrong=Object.values(records.filter(r=>!r.firstTryCorrect).reduce<Record<string,AnswerRecord[]>>((a,r)=>{(a[r.word]??=[]).push(r);return a},{}));const pairs=Object.entries(records.filter(r=>r.confusedWith).reduce<Record<string,number>>((a,r)=>{const k=`${r.word}|${r.confusedWith}`;a[k]=(a[k]??0)+1;return a},{}));return <><ParentHeader titleText="錯題分析" subtitle="找出需要再次練習的單詞"/><section className="panel table-panel"><table><thead><tr><th>單詞</th><th>做錯次數</th><th>最近做錯</th><th>題型</th><th>分類</th><th>錯題再做</th></tr></thead><tbody>{wrong.map(rs=><tr key={rs[0].word}><td>{rs[0].word}</td><td>{rs.length}</td><td>{rs.at(-1)!.date.slice(0,10)}</td><td>{rs.at(-1)!.questionType}</td><td>{rs[0].category}</td><td>{records.some(r=>r.word===rs[0].word&&r.mode==='wrong-redo')?'已練習':'未練習'}</td></tr>)}</tbody></table>{!wrong.length&&<Empty/>}</section><section className="panel"><h2>混淆詞分析</h2><div className="history-list">{pairs.map(([p,c])=><div key={p}><span>Hattie 經常把 <strong>{p.split('|')[0]}</strong> 選成 <strong>{p.split('|')[1]}</strong></span><b>{c} 次</b></div>)}</div>{!pairs.length&&<Empty/>}</section></>}
function RewardsPage(){const rewards=useGardenStore(s=>s.rewards),w=useGardenStore(s=>s.wallet),redeem=useGardenStore(s=>s.redeem),adjust=useGardenStore(s=>s.adjustStars),add=useGardenStore(s=>s.addReward),toggle=useGardenStore(s=>s.toggleReward);const[msg,setMsg]=useState(''),[name,setName]=useState(''),[cost,setCost]=useState(10);const use=(r:Reward)=>{if(!confirm(`確認兌換？將使用 ${r.cost} 分兌換「${r.name}」。`))return;setMsg(redeem(r)?`兌換成功，已使用 ${r.cost} 分。`:'分數不足，暫時不能兌換。')};return <><ParentHeader titleText="獎勵商店" subtitle="只有家長可以替 Hattie 兌換獎勵"/><div className="wallet-strip"><Star fill="currentColor"/><div><span>可用分數</span><strong>{w.currentStars} 分</strong></div><button onClick={()=>adjust(5,'家長手動加分')}>手動加 5 分</button><button onClick={()=>adjust(-5,'家長手動扣分')}>手動扣 5 分</button></div>{msg&&<div className="toast">{msg}</div>}<div className="reward-grid">{rewards.map(r=><article className={!r.enabled?'disabled':''} key={r.id}><Gift/><div><h3>{r.name}</h3><strong>{r.cost} 分</strong></div><button disabled={!r.enabled} onClick={()=>use(r)}>兌換</button><button className="text-button" onClick={()=>toggle(r.id)}>{r.enabled?'停用':'啟用'}</button></article>)}</div><section className="panel add-reward"><h2>新增獎勵</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="獎勵名稱"/><input aria-label="需要分數" type="number" value={cost} onChange={e=>setCost(Number(e.target.value))}/><button onClick={()=>{if(name&&cost>0){add(name,cost);setName('')}}}><Plus/>新增</button></section></>}
function SettingsPage(){const w=useGardenStore(s=>s.wallet),limit=useGardenStore(s=>s.setDailyLimit),sound=useGardenStore(s=>s.soundEnabled),setSound=useGardenStore(s=>s.setSound),show=useGardenStore(s=>s.showPlantWord),setShow=useGardenStore(s=>s.setShowPlantWord),clear=useGardenStore(s=>s.clearData),records=useGardenStore(s=>s.records),sessions=useGardenStore(s=>s.sessions),history=useGardenStore(s=>s.starHistory);const exp=()=>{const b=new Blob([JSON.stringify({records,sessions,wallet:w,starHistory:history},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`hattie-${dayKey()}.json`;a.click()};return <><ParentHeader titleText="設定" subtitle="管理這台 iPad 的本機資料"/><section className="panel settings-list"><label><span><Star/>每日最高得分</span><input type="number" value={w.dailyLimit} onChange={e=>limit(Number(e.target.value))}/></label><label><span><Volume2/>語音播放</span><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/></label><label><span><Sprout/>植物題顯示英文單詞</span><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/></label><button onClick={exp}><Download/>導出學習資料</button><button className="danger-button" onClick={async()=>{if(confirm('確定要清空所有資料嗎？')&&confirm('資料無法恢復，仍要清空嗎？'))await clear()}}><Trash2/>清空資料</button></section></>}
function Empty(){return <div className="empty"><Sprout/><p>暫時沒有資料</p></div>}

export default function App(){const hydrate=useGardenStore(s=>s.hydrate),ready=useGardenStore(s=>s.hydrated);useEffect(()=>{hydrate()},[hydrate]);if(!ready)return <div className="loading">Growing Hattie's garden...</div>;return <Routes><Route path="/" element={<HomePage/>}/><Route path="/review" element={<ReviewPage/>}/><Route path="/plants" element={<PlantsPage/>}/><Route path="/garden" element={<GardenPage/>}/><Route path="/parent-login" element={<ParentLogin/>}/><Route path="/parent" element={<ParentLayout/>}><Route index element={<Dashboard/>}/><Route path="history" element={<HistoryPage/>}/><Route path="weak-words" element={<WeakWordsPage/>}/><Route path="rewards" element={<RewardsPage/>}/><Route path="settings" element={<SettingsPage/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
