import { Check,ChevronLeft,ChevronRight,ImageOff,Languages,Pencil,RefreshCw,Star,Volume2 } from 'lucide-react'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { chineseDictationChars,chineseWords,type ChineseWordItem } from './chineseData'
import { createChineseLevels,createChineseQuestions,initialChineseProgress,type ChineseProgress,type ChineseQuestion,type ChineseQuestionType,type ChineseRecord } from './chineseLogic'
import { calculateScore } from './logic'
import { WritingCanvas } from './WritingCanvas'
import { useGardenStore } from './store'

const storageKey='hattie-chinese-progress'
const loadProgress=():ChineseProgress=>{try{return JSON.parse(localStorage.getItem(storageKey)||'null')||initialChineseProgress()}catch{return initialChineseProgress()}}
const saveProgress=(progress:ChineseProgress)=>{localStorage.setItem(storageKey,JSON.stringify(progress));window.dispatchEvent(new Event('chinese-progress'))}
const speakMandarin=(text:string)=>{if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='zh-CN';utterance.rate=.72;utterance.voice=speechSynthesis.getVoices().find(voice=>voice.lang.toLowerCase().startsWith('zh'))??null;speechSynthesis.speak(utterance)}
const label:Record<ChineseQuestionType,string>={'zh-picture-to-word':'看圖選詞','zh-word-to-picture':'看詞選圖','zh-listen-to-picture':'聽音選圖'}

function ZhShell({children}:{children:React.ReactNode}){return <main className="zh-shell paper-scene"><header><Link to="/zh" aria-label="返回中文首頁"><ChevronLeft/></Link><strong>Hattie 中文小花園</strong><span><Star fill="currentColor"/> 中文</span></header>{children}</main>}
function ZhImage({item,large=false}:{item:ChineseWordItem;large?:boolean}){const[failed,setFailed]=useState(false);return <div className={`zh-image ${large?'large':''}`}>{failed?<ImageOff/>:<img alt="" src={item.image} onError={()=>setFailed(true)}/>}</div>}
function Progress({completed,level,total=60}:{completed:number;level:number;total?:number}){return <div className="zh-progress"><div><span>中文總進度</span><strong>{completed} / {total}</strong><small>第 {level+1} 關</small></div><i><b style={{width:`${completed/total*100}%`}}/></i></div>}

export function LanguageSelect(){return <main className="language-select paper-scene"><section><p>Hi Hattie!</p><h1>今天想複習什麼？</h1><div><Link to="/en"><Languages/><strong>English</strong><span>英文花園</span></Link><Link to="/zh"><span className="hanzi-icon">字</span><strong>中文</strong><span>中文小花園</span></Link></div></section></main>}

export function ChineseHome(){const[progress,setProgress]=useState(loadProgress);useEffect(()=>{const handler=()=>setProgress(loadProgress());window.addEventListener('chinese-progress',handler);return()=>window.removeEventListener('chinese-progress',handler)},[]);return <ZhShell><section className="zh-home"><Progress completed={progress.reviewedWordIds.length} level={progress.currentLevel}/><div className="zh-actions"><Link to="/zh/picture-to-word"><span>圖</span><strong>看圖選詞</strong></Link><Link to="/zh/word-to-picture"><span>詞</span><strong>看詞選圖</strong></Link><Link to="/zh/listen-to-picture"><Volume2/><strong>聽音選圖</strong></Link><Link to="/zh/dictation"><Pencil/><strong>默寫練習</strong></Link></div></section></ZhShell>}

export function ChineseQuiz({type}:{type:ChineseQuestionType}){
  const adjustStars=useGardenStore(state=>state.adjustStars)
  const[progress,setProgress]=useState(loadProgress),levels=useMemo(()=>createChineseLevels(chineseWords),[])
  const[level,setLevel]=useState(Math.min(progress.currentLevel,levels.length-1)),[questions,setQuestions]=useState(()=>createChineseQuestions(levels[Math.min(progress.currentLevel,levels.length-1)],type,chineseWords))
  const[index,setIndex]=useState(0),[result,setResult]=useState<ChineseRecord|null>(null),[records,setRecords]=useState<ChineseRecord[]>([]),[complete,setComplete]=useState(false)
  const q=questions[index],completedBefore=level*10,allCompleted=Math.min(60,completedBefore+index+Number(!!result))
  const choose=(answer:string)=>{if(result)return;const correct=answer===q.item.text,record:ChineseRecord={id:crypto.randomUUID(),word:q.item.text,questionType:type,correctAnswer:q.item.text,selectedAnswer:answer,isCorrect:correct,firstTryCorrect:correct,date:new Date().toISOString()};setResult(record);setRecords(old=>[...old,record]);speakMandarin(q.item.audioText)}
  const next=()=>{if(index===questions.length-1){const reviewed=[...new Set([...progress.reviewedWordIds,...questions.map(question=>question.item.id)])],nextProgress={...progress,reviewedWordIds:reviewed,currentLevel:Math.min(5,level+1),records:[...progress.records,...records]};saveProgress(nextProgress);setProgress(nextProgress);adjustStars(calculateScore(records.filter(record=>record.firstTryCorrect).length,questions.length),'完成中文練習');setComplete(true)}else{setIndex(value=>value+1);setResult(null)}}
  const begin=(nextQuestions:ChineseQuestion[])=>{setQuestions(nextQuestions);setIndex(0);setResult(null);setRecords([]);setComplete(false)}
  if(complete){const wrong=questions.filter(question=>records.some(record=>record.word===question.item.text&&!record.firstTryCorrect)),score=calculateScore(records.filter(record=>record.firstTryCorrect).length,questions.length),hasNext=level<levels.length-1;return <ZhShell><section className="zh-complete"><div className="score-badge"><Star fill="currentColor"/><strong>{score}</strong><span>分</span></div><h1>完成第 {level+1} 關！</h1><Progress completed={Math.min(60,(level+1)*10)} level={level}/><div className="finish-actions with-continue"><Link to="/zh">退出</Link><button disabled={!wrong.length} onClick={()=>begin(wrong)}>錯題再做</button><button onClick={()=>begin(createChineseQuestions(levels[level],type,chineseWords))}><RefreshCw/>重做</button>{hasNext&&<button className="continue-level" onClick={()=>{const nextLevel=level+1;setLevel(nextLevel);begin(createChineseQuestions(levels[nextLevel],type,chineseWords))}}>繼續下一關<ChevronRight/></button>}</div></section></ZhShell>}
  const state=(answer:string)=>!result?'':answer===result.correctAnswer?'option-correct':answer===result.selectedAnswer?'option-wrong':'option-muted'
  return <ZhShell><section className="zh-task"><Progress completed={allCompleted} level={level}/><div className="progress"><span style={{width:`${(index+1)/questions.length*100}%`}}/></div><p className="eyebrow">{label[type]} · {index+1} / {questions.length}</p><div className="zh-prompt">{type==='zh-picture-to-word'?<ZhImage item={q.item} large/>:type==='zh-listen-to-picture'?<button className="zh-listen-main" onClick={()=>speakMandarin(q.item.audioText)}><Volume2/>聽一聽</button>:<><h2>{q.item.text}</h2><button onClick={()=>speakMandarin(q.item.audioText)}><Volume2/>聽一聽</button></>}</div><div className="zh-options">{q.options.map((item,optionIndex)=><button key={item.id} className={state(item.text)} disabled={!!result} aria-label={type==='zh-picture-to-word'?item.text:`圖片選項 ${optionIndex+1}`} onClick={()=>choose(item.text)}>{type==='zh-picture-to-word'?<strong>{item.text}</strong>:<ZhImage item={item}/>}</button>)}</div>{result&&<div className={`zh-feedback ${result.isCorrect?'correct':'wrong'}`}><Check/><div><h3>{result.isCorrect?'答對了！':'差一點點！'}</h3><p>正確答案是：{q.item.text}</p></div><button onClick={next}>下一題<ChevronRight/></button></div>}</section></ZhShell>
}

export function ChineseDictation(){
  const[progress,setProgress]=useState(loadProgress),[index,setIndex]=useState(0),[actions,setActions]=useState<{clear:()=>void;toDataURL:()=>string}|null>(null),[checking,setChecking]=useState(false),[feedback,setFeedback]=useState<{similarity:number;isCorrect:boolean;feedback:string}|null>(null)
  const showTarget=localStorage.getItem('hattie-show-dictation-target')!=='false'
  const item=chineseDictationChars[index]
  const ready=useCallback((value:{clear:()=>void;toDataURL:()=>string})=>setActions(value),[])
  const submit=async()=>{if(!actions||checking)return;setChecking(true);setFeedback(null);try{const response=await fetch('/api/handwriting/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetChar:item.char,imageBase64:actions.toDataURL()})});const result=await response.json();setFeedback(result);const record:ChineseRecord={id:crypto.randomUUID(),word:item.char,questionType:'zh-dictation',correctAnswer:item.char,selectedAnswer:'handwriting',isCorrect:!!result.isCorrect,firstTryCorrect:!!result.isCorrect,date:new Date().toISOString(),similarity:Number(result.similarity)||0};const next={...progress,records:[...progress.records,record]};saveProgress(next);setProgress(next)}catch{setFeedback({similarity:0,isCorrect:false,feedback:'識別暫時不可用，請稍後再試。'})}finally{setChecking(false)}}
  const next=()=>{setIndex(value=>(value+1)%chineseDictationChars.length);actions?.clear();setFeedback(null)}
  return <ZhShell><section className="dictation-page"><div className="dictation-guide"><p className="eyebrow">默寫練習 · {index+1}/{chineseDictationChars.length}</p>{showTarget?<h1>{item.char}</h1>:<div className="hidden-target">?</div>}<button onClick={()=>speakMandarin(item.audioText)}><Volume2/>聽一聽</button><p>{showTarget?'請在右邊的田字格寫出這個字。':'仔細聽，再把字寫在田字格裡。'}</p>{feedback&&<div className={feedback.isCorrect?'dictation-good':'dictation-try'}><h2>{feedback.isCorrect?'寫得很好！':'再試一次！'}</h2><strong>相似度：{feedback.similarity}%</strong><p>{feedback.feedback}</p></div>}</div><div className="dictation-work"><WritingCanvas onReady={ready}/><div><button onClick={()=>actions?.clear()}>清除</button><button onClick={submit} disabled={checking}>{checking?'正在識別…':'完成'}</button>{feedback&&<button onClick={next}>下一題</button>}</div></div></section></ZhShell>
}
